# Generated by Django 3.2 on 2022-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20220522_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_slug',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
