# Generated by Django 3.2 on 2022-07-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20220529_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileimage',
            name='parent_ortho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.orthoimage'),
        ),
    ]
