# Generated by Django 3.2 on 2022-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20220710_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthoimage',
            name='tile_coordinates',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
